CREATE DATABASE IF NOT EXISTS librarydb;
USE librarydb;

CREATE TABLE Books (
    BookId INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(20) NOT NULL UNIQUE,
    Title VARCHAR(255) NOT NULL,
    Author VARCHAR(255) NOT NULL,
    IsAvailable BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE Borrow (
    BorrowId INT AUTO_INCREMENT PRIMARY KEY,
    BookId INT NOT NULL,
    BorrowDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BookId) REFERENCES Books(BookId)
);



-- pantanggal database

USE librarydb;
SET SQL_SAFE_UPDATES = 0;

DELETE FROM Borrow;
DELETE FROM Books;
SET SQL_SAFE_UPDATES = 1;

